# This file was generated by GoReleaser. DO NOT EDIT.
cask "fluidctl" do
  desc "Fluidctl CLI"
  homepage "https://github.com/fluidstackio/atlas"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fluidctl"

  on_macos do
    on_intel do
      url "https://github.com/fluidstackio/atlas/releases/download/fluidctl-v0.1.0/fluidctl_Darwin_x86_64.tar.gz"
      sha256 "f0b0c8dcb24b5c91d508648a91c102bd6805ada0a5ea394af847b388facac462"
    end
    on_arm do
      url "https://github.com/fluidstackio/atlas/releases/download/fluidctl-v0.1.0/fluidctl_Darwin_arm64.tar.gz"
      sha256 "0fd1abbb91004bbbeac404be5ed5a78b538336bc4630b3906ddebd36e1770418"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fluidstackio/atlas/releases/download/fluidctl-v0.1.0/fluidctl_Linux_x86_64.tar.gz"
      sha256 "a5146fdd80dd761e23141939f49069001fda9f1194cc48dd04424193c1bc8292"
    end
    on_arm do
      url "https://github.com/fluidstackio/atlas/releases/download/fluidctl-v0.1.0/fluidctl_Linux_arm64.tar.gz"
      sha256 "3c94c10f5abb38e9f7e3e23258f6f654109bd2cbe3b868ab40f3c5c2d0e3de06"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fluidctl"]
    end
  end

  # No zap stanza required
end
