# This file was generated by GoReleaser. DO NOT EDIT.
cask "fluidctl" do
  name "fluidctl"
  desc "Fluidctl CLI"
  homepage "https://github.com/fluidstackio/atlas"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fluidctl"

  on_macos do
    on_intel do
      url "https://github.com/fluidstackio/atlas/releases/download/fluidctl-v#{version}/fluidctl_Darwin_x86_64.tar.gz"
      sha256 "577fa5526914ed96759ee88cde4226d6c40037e588146af9a567c13b74b91bfb"
    end
    on_arm do
      url "https://github.com/fluidstackio/atlas/releases/download/fluidctl-v#{version}/fluidctl_Darwin_arm64.tar.gz"
      sha256 "76a09c066f02b7b2676d4860d98c80c46410e494872e52d1fb369ac572a91b9b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fluidstackio/atlas/releases/download/fluidctl-v#{version}/fluidctl_Linux_x86_64.tar.gz"
      sha256 "f310e76730bb183147344824bd6a09c9fa34a47d222845c407c2db60941bbc7c"
    end
    on_arm do
      url "https://github.com/fluidstackio/atlas/releases/download/fluidctl-v#{version}/fluidctl_Linux_arm64.tar.gz"
      sha256 "f5c4f2e8d698abdcc33121f12bbd0f82dfb5a18a0b08443a32dbf121f40e4bc6"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fluidctl"]
    end
  end

  # No zap stanza required
end
