# This file was generated by GoReleaser. DO NOT EDIT.
cask "fluidctl" do
  name "fluidctl"
  desc "Fluidctl CLI"
  homepage "https://docs.fluidstack.io"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fluidctl"

  on_macos do
    on_intel do
      url "https://github.com/fluidstackio/atlas-releases/releases/download/fluidctl-v#{version}/fluidctl_Darwin_x86_64.tar.gz"
      sha256 "b13b017f79e359282dd188108d6d807cc86d6836a0e905f693ea33af6a59f0af"
    end
    on_arm do
      url "https://github.com/fluidstackio/atlas-releases/releases/download/fluidctl-v#{version}/fluidctl_Darwin_arm64.tar.gz"
      sha256 "d85d2a8787fa453065641021bda3dc0bc1beff3e874e2b37f97a22a3ccdf5c31"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fluidstackio/atlas-releases/releases/download/fluidctl-v#{version}/fluidctl_Linux_x86_64.tar.gz"
      sha256 "b39eb98970b2bf7fcaf4ae1782bc810ce7d7d267fbc57282f0aa86e825fa488c"
    end
    on_arm do
      url "https://github.com/fluidstackio/atlas-releases/releases/download/fluidctl-v#{version}/fluidctl_Linux_arm64.tar.gz"
      sha256 "1d31d17f3d5e384cb9486cc07dc11c76fa45b79435895ae8e2a5c89ccd745b39"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fluidctl"]
    end
  end

  # No zap stanza required
end
